# loOS Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Workspace rules
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0

# Window rules for specific workspaces
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]

# Walker launcher layer rules
layerrule = no_anim on, match:namespace walker
layerrule = blur true, match:namespace walker
layerrule = ignore_alpha 0.5, match:namespace walker
